# Generated by Django 4.2.1 on 2025-05-12 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImprovementProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Регистрационный номер')),
                ('submission_date', models.DateField(verbose_name='Дата подачи предложения')),
                ('department', models.CharField(max_length=100, verbose_name='Подразделение')),
                ('participation_coefficient', models.PositiveIntegerField(default=100, verbose_name='Коэффициент участия')),
                ('current_situation', models.TextField(verbose_name='Существующая ситуация (проблема)')),
                ('current_situation_sketch', models.FileField(blank=True, null=True, upload_to='ppu/sketches/', verbose_name='Эскиз текущей ситуации')),
                ('proposed_solution', models.TextField(verbose_name='Предлагаемое решение')),
                ('solution_sketch', models.FileField(blank=True, null=True, upload_to='ppu/sketches/', verbose_name='Эскиз решения')),
                ('expected_result', models.TextField(verbose_name='Ожидаемый результат (эффект)')),
                ('ready_to_implement', models.BooleanField(default=False, verbose_name='Готов внедрить самостоятельно')),
                ('required_resources', models.TextField(blank=True, verbose_name='Необходимые ресурсы')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подано'), ('review', 'На рассмотрении'), ('approved', 'Утверждено'), ('rejected', 'Отклонено'), ('implemented', 'Внедрено')], default='draft', max_length=20, verbose_name='Статус')),
                ('document', models.FileField(blank=True, null=True, upload_to='ppu/documents/', verbose_name='Документ ППУ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_proposals', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Предложение по улучшению',
                'verbose_name_plural': 'Предложения по улучшению',
                'ordering': ['-created_at'],
            },
        ),
    ]
