# Generated by Django 4.2.1 on 2025-05-13 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('www', '0002_improvementproposal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(choices=[('xml', 'XML'), ('xlsx', 'Excel'), ('csv', 'CSV'), ('json', 'JSON'), ('mxl', '1C MXL (Комплектация)'), ('other', 'Other')], max_length=50),
        ),
    ]
